# Generated by Django 3.1.7 on 2021-03-30 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='api.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='api.review'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='api.image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.store'),
        ),
        migrations.AddField(
            model_name='friend',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_from', to='api.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to='api.profile'),
        ),
        migrations.AddField(
            model_name='favoritestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_store', to='api.store'),
        ),
        migrations.AddField(
            model_name='favoritestore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_store', to='api.profile'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='api.product'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='api.profile'),
        ),
        migrations.AddField(
            model_name='couponselling',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_selling', to='api.coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='api.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='api.profile'),
        ),
        migrations.AddField(
            model_name='centralnotice',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='central_notice', to='api.article'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='api.article'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='api.image'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='usermenuitem',
            unique_together={('user', 'menu_item')},
        ),
        migrations.AlterUniqueTogether(
            name='storetag',
            unique_together={('store', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='storereview',
            unique_together={('store', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='storenotice',
            unique_together={('article', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='storeimage',
            unique_together={('store', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'review')},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritestore',
            unique_together={('store', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='articleimage',
            unique_together={('article', 'image')},
        ),
    ]
